AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**
    - config/**
    - script/**
    - spec/**
Layout/TrailingEmptyLines:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/RedundantInterpolation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
