# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51782ce8802bd88d0a43abda9063db80e44ac3855de7a056295a8805d747ba94bd2c4d4d8229b4ff20d6a770f94d1aaa4417cce824b9249c6952d50919fdcc0e

test:
  secret_key_base: 1fefa509734b852ea257c6bf63fff74798bd15d9b40fea36eaf1c0607710f4b74c5f599112d202b70a9b93c68432b7505223737405f01315f295e865b6999418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
