#!/bin/bash
# Create the fstab

# Add some mount options depending on the filesystem
case $filesystem in
	ext2) mountoptions+=',barrier=0' ;;
	ext3) mountoptions+=',barrier=0' ;;
	ext4) mountoptions+=',barrier=0' ;;
	xfs)  mountoptions+=',nobarrier' ;;
	*)    ;;
esac

cat >> $imagedir/etc/fstab <<EOF
/dev/xvda1           /boot ext2 defaults 1 2
/dev/vg_root/lv_root /     $filesystem defaults$mountoptions 1 1
/dev/mapper/vg_root-lv_swap none swap sw 0 0
none /proc proc defaults 0 0
none /sys sysfs defaults 0 0
EOF
