#!/bin/bash
# Update standard packages to the backports version.

if $use_backports_packages; then
log 'Installing Backports Packages'
chroot $imagedir apt-get -t ${codename}-backports -q -y install ${ssh_packages}
fi
