#!/bin/bash
# Add GCE startup scripts and packages to the image.

DEBS="google-compute-daemon google-startup-scripts python-gcimagebundle"
for deb in $DEBS; do
  chroot $imagedir apt-get install --force-yes -q -y ${deb}
done
