#!/bin/bash
# Prepare GRUB to install itself correctly.

# Set up a device map for GRUB to use while loopback-mounted:
echo "(hd0) ${base_device_path}" > $imagedir/boot/grub/device.map
echo "(hd0,1) ${device_path}" >> $imagedir/boot/grub/device.map

# Configure GRUB timeouts for fast booting:
sed -i -e '/GRUB_TIMEOUT=/s/^.*/GRUB_TIMEOUT=0/' $imagedir/etc/default/grub

# Direct GRUB and Linux console output to ttyS0 to facilitate gcutil
# getserialportoutput.
#
# The backreference on the next line avoids spurious spaces in the resulting
# kernel command line.
sed -i -e '/GRUB_CMDLINE_LINUX=/s/\( \)\?"$/\1console=ttyS0,38400n8"/' \
    $imagedir/etc/default/grub
sed -i -e '/GRUB_TERMINAL=/s/^.*/GRUB_TERMINAL="serial --unit=0 --speed=38400 --word=8 --parity=no --stop=1"' \
    $imagedir/etc/default/grub
