#!/bin/bash
#
# No IPv6 networking is currently available in Google Compute Engine.
# To minimize risk of software misbehavior, disable IPv6 by default.
# This can be reverted if Google Compute Engine adds IPv6 support or
# removed by any user wanting to use IPv6 via loopback or IPv4-tunneled
# interfaces.

cat >> $imagedir/etc/sysctl.d/70-disable-ipv6.conf <<EOF
net.ipv6.conf.all.disable_ipv6 = 1
EOF
