#!/bin/bash
# Install GRUB in the MBR of the image and do necessary cleanup

# Install GRUB:
chroot $imagedir grub-install "${base_device_path}"

# Remove loopback-specific device map:
rm $imagedir/boot/grub/device.map

# Remove loopback-specific grub.cfg lines added by a Debian/Ubuntu GRUB patch
# meant for a different use case:
sed -i -e '/loop/d' $imagedir/boot/grub/grub.cfg
