#!/bin/bash

# lvm-root-volume
# Put the root volume on an LVM partition

if [ $volume_size -lt 2 ]
then
  die "Disk must be at least 2 GB"
fi

insert_task_after $TASK_PACKAGES $plugindir/lvm-root-volume-tasks/01-lvm-package

remove_task "12-format-volume"
insert_task_after "11-attach-volume" "$plugindir/lvm-root-volume-tasks/12-partition-and-format-volume"
remove_task $TASK_MOUNT_VOLUME
insert_task_before $TASK_BOOTSTRAP "$plugindir/lvm-root-volume-tasks/13-mount-volume"


remove_task "30-grub"
insert_task_after "22-apt-upgrade" "$plugindir/lvm-root-volume-tasks/30-grub"
remove_task "31-fstab"
insert_task_after "30-grub" "$plugindir/lvm-root-volume-tasks/31-fstab"

insert_task_after "51-init-scripts" "$plugindir/lvm-root-volume-tasks/52-replace-expand-volume"

insert_task_before $TASK_UNMOUNT_VOLUME "$plugindir/lvm-root-volume-tasks/72-unmount-boot"
insert_task_before "73-detach-volume" "$plugindir/lvm-root-volume-tasks/73-deactivate-vg"
remove_task $TASK_CREATE_AMI
insert_task_after $TASK_DELETE_VOLUME "$plugindir/lvm-root-volume-tasks/95-register-ami"
