package: github.com/netlify/netlifyctl
import:
- package: github.com/BurntSushi/toml
  version: master
- package: github.com/sirupsen/logrus
  version: v0.11.0
- package: github.com/go-openapi/errors
- package: github.com/go-openapi/runtime
  version: 96511efa8f2190cf4dd04412c61a1a96546b36d9
  subpackages:
  - client
- package: github.com/go-openapi/strfmt
- package: github.com/netlify/open-api
  version: 09203f5c1873bd4124acdd7929651cb29d2bc3c2
  vcs: git
  subpackages:
  - go/models
  - go/porcelain
  - go/porcelain/context
- package: github.com/spf13/cobra
- package: github.com/skratchdot/open-golang
- package: github.com/mitchellh/go-homedir
- package: gopkg.in/src-d/go-git.v4
- package: github.com/github/hub
  subpackages:
  - github
- package: github.com/google/go-github
  version: 35c06c17eff17d6ba18c6d8c5a84827f8ecf8679
- package: golang.org/x/sys
  version: 1e2299c37cc91a509f1b12369872d27be0ce98a6
- package: github.com/briandowns/spinner
  version: b2e0b668d1ae4a3959df7d1ed2c18927d65ad1e1
  repo: https://github.com/calavera/spinner
- package: github.com/Azure/go-autorest
  version: ~9.6.0
  subpackages:
  - autorest
- package: github.com/pkg/errors
- package: github.com/xanzy/go-gitlab
  version: 8a20d674959fea44da3d253bdd883f2c3d280310
testImport:
- package: github.com/stretchr/testify
  subpackages:
  - require
