extends: 
  - chartjs
  - esnext

parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    modules: true
    experimentalObjectRestSpread: true

env:
  browser: true
  es6: true
  node: true

parser: babel-eslint