backend:
  name: github-api
  repo: netlify/swt # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "static/uploads" # Folder where user uploaded files should go
public_folder: "static"

collections: # A list of collections the CMS should be able to edit
  - name: "presentations" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Presentation" # Used in the UI, ie.: "New Post"
    folder: "content/presentations" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Presenter", name: "presenter", widget: "string"}
      - {label: "Presenter Title (CEO/CMO/etc)", name: "presenter_title", widget: "string"}
      - {label: "Location (Wikia/Netlify HQ/etc)", name: "location", widget: "string"}
      - {label: "Description", name: "description", widget: "string", tagname: "p", class: "lead"}
      - {label: "Cover Image", name: "cover", widget: "image", media_folder: "static/img/presentations"}
      - {label: "Youtube Embed", name: "youtube", widget: "string"}
      - {label: "Speakerdeck Embed", name: "speakerdeck", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "date"}

  - name: "upcoming" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Upcoming" # Used in the UI, ie.: "New Post"
    folder: "content/upcoming" # The path to the folder where the documents are stored
    sort: "date:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Presenter", name: "presenter", widget: "string"}
      - {label: "Presenter Title (CEO/CMO/etc)", name: "presenter_title", widget: "string"}
      - {label: "Location (Wikia/Netlify HQ/etc)", name: "location", widget: "string"}
      - {label: "Description", name: "description", widget: "string", tagname: "p", class: "lead"}
      - {label: "Cover Image", name: "cover", widget: "image", media_folder: "static/img/upcoming"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "date"}
