package: github.com/netlify/elastinats
import:
- package: github.com/Sirupsen/logrus
  version: v0.10.0
- package: github.com/nats-io/nats
  version: v1.2.0
- package: github.com/spf13/cobra
- package: github.com/spf13/viper
testImport:
- package: github.com/stretchr/testify
  version: v1.1.4
  subpackages:
  - assert
