name: episodes
author: "Dart Episodes Authors <web-ui-dev@dartlang.org>"
homepage: https://github.com/dart-lang/episodes
description: A library for timing performance of web apps.
version: 0.4.0+1
environment:
  sdk: ">=1.0.0 <2.0.0"
