#!/bin/bash
# Add some basic packages we are going to need
packages+=('udev')
packages+=('openssh-server')
# We could bootstrap without locales, but things just suck without them,
# error messages etc.
packages+=('locales')
# Needed for the init scripts
packages+=('file')

packages+=('grub-pc')

# We will need to format the volume, so we need xfsprogs
[ $filesystem = 'xfs' ] && host_packages+=('xfsprogs')
# In order to make sure a volume is not busy, before unmounting we need lsof
host_packages+=('lsof')
host_packages+=('debootstrap')

# Force noninteractive mode for apt-get
export DEBIAN_FRONTEND='noninteractive'
