# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83bb395e4f1351acd88482b8faaff61e22665872948a57a516e220c1a7503ed82364f1b88c103535ca4c0a8deda9614ecfaa5f7db9dc90c549e0ebfd4f03eda9

test:
  secret_key_base: 1ea3a80f989fde7f5c7549c17355ab2161a79672de6d88d0caeda192a21d7035aacfbe0a66c1ed83767226c2a24eed5821ecedd382c9bd44fe7c4d7eec4b5930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
