#!/bin/bash

# Format the volume with a boot partition then the rest LVM
sfdisk $device_path << EOF
,20,L
,,8e
EOF

boot_device_path=${device_path}1
lvm_device_path=${device_path}2

log "Formatting the boot device $boot_device_path with ext2"
mkfs.ext2 $boot_device_path

log "Creating LVM Volumes on $lvm_device_path"
pvcreate $lvm_device_path
vgcreate vg_root $lvm_device_path

log "Creating swap"
lvcreate -nlv_swap -L1G vg_root
mkswap /dev/mapper/vg_root-lv_swap

lvcreate -nlv_root -l100%FREE vg_root
root_device_path=/dev/mapper/vg_root-lv_root
log "Formatting the device $root_device_path with $filesystem"
mkfs.$filesystem $root_device_path

case $filesystem in
	# Disable time based fs checks
	ext*) tune2fs -i 0 $root_device_path ;;
	# Add some tools for xfs, ext tools are built-in
	xfs)  packages+=('xfsprogs')    ;;
esac
