#!/bin/bash
# Mount the EBS volume
imagedir=$debootstrap_dir/${volume_id}

# Fail if the imagedir exists, it should be quite unique.
# This guarantees that we later on can delete it without having to check for anything.
if [ -d "$imagedir" ]; then
	die "The mount location $imagedir already exists."
fi
# Create the dir we are going to mount the volume onto
mkdir -p $imagedir

[ -n "`mount | grep "$imagedir"`" ] && die "Something is already mounted on $imagedir"

mount $root_device_path $imagedir
mkdir -p $imagedir/boot
mount $boot_device_path $imagedir/boot

log "The volume is mounted at ${imagedir}."
