#!/bin/bash
# Register the snapshot as a new AMI

# Figure out which pvGrub kernel ID we need - make sure to use the hd00 kernel since we have partitioned the root disk...
case $region in
	us-east-1)
		[ $arch = 'amd64' ] && aki="aki-b4aa75dd"
		[ $arch = 'i386' ] && aki="aki-b2aa75db"
	;;
	us-west-1)
		[ $arch = 'amd64' ] && aki="aki-eb7e26ae"
		[ $arch = 'i386' ] && aki="aki-e97e26ac"
	;;
	us-west-2)
		[ $arch = 'amd64' ] && aki="aki-f837bac8"
		[ $arch = 'i386' ] && aki="aki-f637bac6"
	;;
	eu-west-1)
		[ $arch = 'amd64' ] && aki="aki-8b655dff"
		[ $arch = 'i386' ] && aki="aki-89655dfd"
	;;
	ap-southeast-1)
		[ $arch = 'amd64' ] && aki="aki-fa1354a8"
		[ $arch = 'i386' ] && aki="aki-f41354a6"
	;;
	ap-southeast-2)
		[ $arch = 'amd64' ] && aki="aki-31990e0b"
		[ $arch = 'i386' ] && aki="aki-33990e09"
	;;
	ap-northeast-1)
		[ $arch = 'amd64' ] && aki="aki-40992841"
		[ $arch = 'i386' ] && aki="aki-3e99283f"
	;;
	sa-east-1)
		[ $arch = 'amd64' ] && aki="aki-c88f51d5"
		[ $arch = 'i386' ] && aki="aki-ce8f51d3"
	;;
	us-gov-west-1)
		[ $arch = 'amd64' ] && aki="aki-75a4c056"
		[ $arch = 'i386' ] && aki="aki-77a4c054"
	;;
	*) die "Unrecognized region:" "$region"
esac


[ $arch = 'i386' ] && ami_arch='i386'
[ $arch = 'amd64' ] && ami_arch='x86_64'

# The AMI has to start with "debian", otherwise we won't get a nice icon
# The ":N:true:standard" is necessary so that the root volume
# will be deleted on termination of the instance (specifically the "true" part)
ami_name="$distribution-$codename-$arch-$name_suffix"
log "Registering an AMI with the snapshot '$snapshot_id'"
ami_id=`euca-register \
	--name "$ami_name" --description "$description" \
	--architecture "$ami_arch" --kernel "$aki" \
	--snapshot "$snapshot_id:$volume_size:true:standard" \
	--root-device-name /dev/sda \
	| awk '{print $2}'`

# If the user has already created an unnamed AMI today,
# this will fail, so give the AMI registration command to the user
if [[ ! "$ami_id" =~ ^ami-[0-9a-z]{8}$ ]]; then
	die \
		"Unable to register an AMI." \
		"You can do it manually with:" \
		"`which euca-register` \\\\" \
		"--name '$ami_name' --description '$description' \\\\" \
		"--architecture '$ami_arch' --kernel '$aki' \\\\" \
		"--snapshot '$snapshot_id:$volume_size:true:standard' \\\\" \
		"--root-device-name /dev/sda"
fi
log "Your AMI has been created with the ID '$ami_id'"
