#!/bin/bash
# Set up loopback devices.

# First the underlying disk...
base_device_path="$(losetup -f --show $workspace/disk.raw)"

if [ $? -ne 0 ]; then
  die "Unable to create volume."
fi

log "Whole-disk loopback device for GCE volume is ${base_device_path}."

# ... then the partition at a 1MB offset. (Avoid the kpartx + /dev/mapper combo
# due to GRUB tools being finicky.)
device_path="$(losetup -o $((1024*1024)) -f --show ${base_device_path})"
log "Partition loopback device for GCE volume is ${device_path}."
