#!/bin/bash

# To be as close to stock Debian as possible, the image should default to the
# standard Debian repository list. Therefore, remove the Google repository and
# GPG key, then update the apt cache once more.

rm $imagedir/etc/apt/sources.list.d/goog.list
google_keyid="$(chroot $imagedir apt-key adv --with-colons --list-keys \
  | awk -F: '$10 ~ /@google\.com/ { print $5 }')"
chroot $imagedir apt-key del ${google_keyid}
chroot $imagedir apt-get update
