#!/bin/bash
# Delete the loopback devices
log "Deleting the loopback devices"
losetup -d $device_path
# Give the system a moment to react to the first losetup -d, without which the
# second losetup -d gives a fatal "Device or resource busy" error.
sleep 1
losetup -d $base_device_path

# Lets cleanup code know the loopback device was deleted.
unset device_path base_device_path
