#!/bin/bash
# Remove the ssh host keys, they need to be shredded
shred --remove \
	$imagedir/etc/ssh/ssh_host_dsa_key \
	$imagedir/etc/ssh/ssh_host_dsa_key.pub \
	$imagedir/etc/ssh/ssh_host_rsa_key \
	$imagedir/etc/ssh/ssh_host_rsa_key.pub
