extends:
  - chartjs
  - plugin:es/no-new-in-es2019
  - plugin:markdown/recommended

env:
  es6: true
  browser: true
  node: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    modules: true

plugins: ['html', 'es']

rules:
  complexity: ["warn", 10]
  max-statements: ["warn", 30]
  no-var: "warn"
  prefer-const: ["warn", {"destructuring": "all"}]
