package: github.com/netlify/streamer
import:
- package: github.com/Sirupsen/logrus
  version: v0.10.0
- package: github.com/hpcloud/tail
  version: v1.0.0
- package: github.com/nats-io/nats
  version: v1.2.0
- package: github.com/spf13/cobra
- package: github.com/spf13/viper
